#!/usr/bin/env python

import sys

if len(sys.argv) > 1 and sys.argv[1] == 'subprocess':
    port = int(sys.argv[2])
    from dreampielib.subprocess import main
    main(port)

else:
    from dreampielib.gui import main
    main(__file__)
