#!/usr/bin/env python

import sys

if len(sys.argv) > 1 and sys.argv[1] == 'subprocess':
    port = int(sys.argv[2])
    from dreampielib.subprocess import main
    main(port)

else:
    if len(sys.argv) > 1 and sys.argv[1] == 'hide-console-window':
        from dreampielib.gui.hide_console_window import hide_console_window
        hide_console_window()
        
    from dreampielib.gui import main
    main(__file__)
